In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr.dtype)

int64


In [6]:
arr2 = np.array([1,2,3,4,5], dtype = np.int16)

In [7]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [8]:
Z = np.zeros(5)

In [9]:
Z

array([0., 0., 0., 0., 0.])

In [10]:
ar = np.arange(0,10,1)

In [11]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ran = np.random.rand(4)

In [13]:
ran

array([0.63406802, 0.46643897, 0.71405534, 0.04834364])

In [15]:
ln = np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

2D array

In [16]:
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
o1 = np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
I = np.eye(5)

In [21]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
r1 = np.random.rand(4,5)
r1

array([[0.19952083, 0.15980892, 0.64805532, 0.1163615 , 0.02273976],
       [0.48844385, 0.6980858 , 0.00445205, 0.35036829, 0.9565512 ],
       [0.1761529 , 0.42036093, 0.79888505, 0.22638571, 0.84620282],
       [0.3158455 , 0.23031958, 0.28472617, 0.37080603, 0.57250772]])

In [25]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(ar.size)

10


In [28]:
print(ar2.size)

9


In [29]:
print(ar2.shape)

(3, 3)


In [30]:
print(ar.dtype)

int64


In [31]:
print(ar2.dtype)

int64


# Operations in Array
**copy**
**sort**
**reshape**

In [33]:
ar3 = np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar3[2,2] = 10

In [35]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [36]:
ar3[1,2]=12
ar3[0,1]=15

In [37]:
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [38]:
ar3 = np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [39]:
ar3 = np.sort(ar3, axis = 0)

In [40]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [41]:
ar3.sum()

np.int64(65)

In [42]:
ar3.sum(axis = 0)

array([12, 16, 37])

In [43]:
ar3.sum(axis = 1)

array([14, 21, 30])

In [44]:
ar4 = np.random.rand(99)
ar4

array([0.10345563, 0.83235964, 0.94866103, 0.07266879, 0.63486583,
       0.84751883, 0.41453195, 0.91706318, 0.71476859, 0.34237763,
       0.12386451, 0.34491462, 0.26796568, 0.83750151, 0.94032285,
       0.43018272, 0.0619767 , 0.05667558, 0.58267271, 0.44279614,
       0.07686643, 0.64582787, 0.11113684, 0.02603767, 0.27075705,
       0.87174884, 0.40980657, 0.76995656, 0.58746358, 0.13677511,
       0.16087258, 0.21464211, 0.16598783, 0.20702286, 0.10042326,
       0.42500617, 0.24387446, 0.26646999, 0.16921348, 0.25394294,
       0.2615197 , 0.09767996, 0.14012996, 0.15233581, 0.48524449,
       0.06470757, 0.69659254, 0.24328229, 0.07468516, 0.66048012,
       0.27729139, 0.62772425, 0.87221268, 0.64634302, 0.45921902,
       0.23533342, 0.16591949, 0.12988076, 0.43618257, 0.88303783,
       0.05181589, 0.42804037, 0.97980225, 0.07721419, 0.46520519,
       0.7867693 , 0.30421489, 0.78451758, 0.54465292, 0.56805028,
       0.69920294, 0.71077786, 0.52702627, 0.20436158, 0.13051

In [45]:
ar4.size

99

In [46]:
ar4.reshape(11,9)

array([[0.10345563, 0.83235964, 0.94866103, 0.07266879, 0.63486583,
        0.84751883, 0.41453195, 0.91706318, 0.71476859],
       [0.34237763, 0.12386451, 0.34491462, 0.26796568, 0.83750151,
        0.94032285, 0.43018272, 0.0619767 , 0.05667558],
       [0.58267271, 0.44279614, 0.07686643, 0.64582787, 0.11113684,
        0.02603767, 0.27075705, 0.87174884, 0.40980657],
       [0.76995656, 0.58746358, 0.13677511, 0.16087258, 0.21464211,
        0.16598783, 0.20702286, 0.10042326, 0.42500617],
       [0.24387446, 0.26646999, 0.16921348, 0.25394294, 0.2615197 ,
        0.09767996, 0.14012996, 0.15233581, 0.48524449],
       [0.06470757, 0.69659254, 0.24328229, 0.07468516, 0.66048012,
        0.27729139, 0.62772425, 0.87221268, 0.64634302],
       [0.45921902, 0.23533342, 0.16591949, 0.12988076, 0.43618257,
        0.88303783, 0.05181589, 0.42804037, 0.97980225],
       [0.07721419, 0.46520519, 0.7867693 , 0.30421489, 0.78451758,
        0.54465292, 0.56805028, 0.69920294, 0.71077786],


In [47]:
ar4.size

99

In [48]:
ar4.shape

(99,)

In [49]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
ar = np.append(ar,10)

In [51]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
ar = np.delete(ar, 6, axis = 0)

In [53]:
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [54]:
ar = np.insert(ar, 6, 6)

In [55]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [60]:
ar4 = np.concatenate((ar2,ar3),axis = 0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [62]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [63]:
ar5 = np.concatenate((ar2,ar3),axis=1)

In [64]:
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [69]:
np.add(ar5,5)

array([[ 6,  7,  8,  6,  8, 15],
       [ 9, 10, 11,  9, 10, 17],
       [12, 13, 14, 12, 13, 20]])

In [71]:
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  2,  9],
       [ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  7, 14]])

In [72]:
np.multiply(ar5,3)

array([[ 3,  6,  9,  3,  9, 30],
       [12, 15, 18, 12, 15, 36],
       [21, 24, 27, 21, 24, 45]])

In [73]:
np.divide(ar5,2)

array([[0.5, 1. , 1.5, 0.5, 1.5, 5. ],
       [2. , 2.5, 3. , 2. , 2.5, 6. ],
       [3.5, 4. , 4.5, 3.5, 4. , 7.5]])